#!/bin/bash

while true; do
  bat_lvl=$(cat /sys/class/power_supply/BAT0/capacity)
  if [ "$bat_lvl" -le 20 ] || [ "$bat_lvl" -le 10 ]; then
    notify-send --urgency=CRITICAL "Battery Low: ${bat_lvl}%"
    sleep 600
  else
    sleep 120
  fi
done
