#!/bin/bash

SESSION_NAME="everything"

if tmux has-session -t $SESSION_NAME 2>/dev/null; then
  echo "Session $SESSION_NAME already exists. Attaching to it."
  tmux attach-session -t $SESSION_NAME
else
  tmux new-session -d -s $SESSION_NAME
  tmux split-window -h
  tmux select-pane -t 1
  tmux resize-pane -R 30
  tmux send-keys -t 1 'yazi' C-m
  tmux send-keys -t 2 'nmtui connect' C-m
  tmux attach-session -t $SESSION_NAME
fi
