#!/usr/bin/env bash

iDIR="$HOME/.config/dunst/icons"

# Get Volume
get_volume() {
  volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2 * 100}')
  echo "${volume%.*}"
}

# Get icons
get_icon() {
  current=$(get_volume)
  if [[ "$current" -eq "0" ]]; then
    echo "$iDIR/volume-mute.png"
  elif [[ ("$current" -gt "0") && ("$current" -le "30") ]]; then
    echo "$iDIR/volume-low.png"
  elif [[ ("$current" -gt "30") && ("$current" -le "60") ]]; then
    echo "$iDIR/volume-mid.png"
  elif [[ ("$current" -gt "60") ]]; then
    echo "$iDIR/volume-high.png"
  fi
}

# Notify
notify_user() {
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume) %"
}

# Increase Volume
inc_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify_user
}

# Decrease Volume
dec_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify_user
}

# Toggle Mute
toggle_mute() {
  if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED; then
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
  else
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 1 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
  fi
}

# Toggle Mic
toggle_mic() {
  if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED; then
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
  else
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
  fi
}

# Get Mic Volume Icon
get_mic_icon() {
  echo "$iDIR/microphone.png"
}

# Notify Mic Volume
notify_mic_user() {
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Mic-Level : $(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | awk '{print $2 * 100}' | cut -d '.' -f 1) %"
}

# Increase Mic Volume
inc_mic_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+ && notify_mic_user
}

# Decrease Mic Volume
dec_mic_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%- && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
  toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
  get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
  get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
  inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
  dec_mic_volume
else
  get_volume
fi
