# Preload the wallpaper image into RAM
preload = ~/Downloads/IMG_3175.jpg

# Set the wallpaper as the default fallback for all monitors
wallpaper = ,~/Downloads/IMG_3175.jpg

# Disable the splash text rendering
splash = false
